// Writes audio-inbox/WANTED.md: the clips the game could use but does not have.
// The owner generates each one, listens, and drops it in the folder named.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const manifest = existsSync('src/content/audio-manifest.json') ? JSON.parse(readFileSync('src/content/audio-manifest.json', 'utf8')) : {};
const words = JSON.parse(readFileSync('src/content/words.json', 'utf8'));
const AREAS = {
  i1a1: { title: 'Island 1, area 1 (a m s t)', letters: 'amst' },
  i1a2: { title: 'Island 1, area 2 (p f i n)', letters: 'pfin' },
  i1a3: { title: 'Island 1, area 3 (o d c)', letters: 'odc' },
  i1a4: { title: 'Island 1, area 4 (u g b e)', letters: 'ugbe' },
};

const lines = [
  '# Audio wanted',
  '',
  'Generated by `npm run audio:wanted`. Drop each finished clip in the folder shown, with the file name shown',
  '(any audio format; WAV preferred), then run `npm run audio`.',
  '',
];
// Spoken prompts the game will use as soon as they exist. Keep them short and reusable.
const PROMPTS = { 'your-turn': 'Your turn!' };
let total = 0;
const prompts = Object.entries(PROMPTS).filter(([id]) => !(`prompts/${id}` in manifest));
if (prompts.length) {
  lines.push('## Prompts', '');
  for (const [id, text] of prompts) lines.push(`- [ ] \`audio-inbox/prompts/${id}.wav\` : "${text}"`);
  lines.push('');
  total += prompts.length;
}
for (const [id, area] of Object.entries(AREAS)) {
  const sounds = [...area.letters].filter((g) => !(`letters/${g}-sound` in manifest));
  const missing = words[id].filter((w) => !(`words/${w}` in manifest));
  lines.push(`## ${area.title}`, '');
  if (!sounds.length && !missing.length) lines.push('Nothing missing.', '');
  for (const g of sounds) lines.push(`- [ ] \`audio-inbox/letters/${g}-sound.wav\` : the isolated sound of "${g}", no trailing "uh"`);
  for (const w of missing) lines.push(`- [ ] \`audio-inbox/words/${w}.wav\` : the word "${w}", said plainly`);
  if (sounds.length || missing.length) lines.push('');
  total += sounds.length + missing.length;
}
for (const f of ['letters', 'words', 'prompts', 'sfx']) mkdirSync(`audio-inbox/${f}`, { recursive: true });
writeFileSync('audio-inbox/WANTED.md', lines.join('\n'));
console.log(`${total} clips wanted; see audio-inbox/WANTED.md`);
